# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     l502-bf_Release
#     l502-bf_Release_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

#ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 5.1.2
ADI_DSP=C:\VisualDSP
MAKECMDGOALS=l502-bf_Release

# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "l502-bf_Release" configuration
#

ifeq ($(MAKECMDGOALS),l502-bf_Release)

l502-bf_Release : ./Release/l502-bf.ldr 

./Release/l502-bf_basiccrt.doj :./l502-bf_basiccrt.s $(VDSP)/Blackfin/include/cplb.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/sys/_adi_platform.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/platform.h 
	@echo ".\l502-bf_basiccrt.s"
	$(VDSP)/easmblkfn.exe .\l502-bf_basiccrt.s -proc ADSP-BF523 -file-attr ProjectName=l502-bf -o .\Release\l502-bf_basiccrt.doj -MM

Release/l502-bf_heaptab.doj :l502-bf_heaptab.c 
	@echo ".\l502-bf_heaptab.c"
	$(VDSP)/ccblkfn.exe -c .\l502-bf_heaptab.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502-bf_heaptab.doj -MM

Release/l502_async.doj :../src/l502_async.c $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib_bf.h ../src/l502_cmd.h $(VDSP)/Blackfin/include/stdint.h ../src/l502_bf_cmd_defs.h ../src/l502_global.h ../src/l502_fpga.h ../src/l502_fpga_regs.h ../src/l502_defs.h ../src/l502_async.h 
	@echo "..\src\l502_async.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_async.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_async.doj -MM

Release/l502_cmd.doj :../src/l502_cmd.c ../src/l502_global.h $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h ../src/l502_bf_cmd_defs.h ../src/l502_cmd.h ../src/l502_stream.h ../src/l502_params.h ../src/l502_defs.h ../src/l502_user_process.h ../src/l502_async.h ../src/l502_sport_tx.h $(VDSP)/Blackfin/include/string.h $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h $(VDSP)/Blackfin/include/sys/exception.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h ../src/l502_fpga.h ../src/l502_fpga_regs.h 
	@echo "..\src\l502_cmd.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_cmd.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_cmd.doj -MM

Release/l502_fpga.doj :../src/l502_fpga.c $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h ../src/l502_fpga.h $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h ../src/l502_fpga_regs.h 
	@echo "..\src\l502_fpga.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_fpga.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_fpga.doj -MM

Release/l502_hdma.doj :../src/l502_hdma.c ../src/l502_global.h $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h ../src/l502_bf_cmd_defs.h ../src/l502_cdefs.h ../src/l502_cmd.h $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h $(VDSP)/Blackfin/include/sys/exception.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h 
	@echo "..\src\l502_hdma.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_hdma.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_hdma.doj -MM

Release/l502_init.doj :../src/l502_init.c $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h $(VDSP)/Blackfin/include/bfrom.h $(VDSP)/Blackfin/include/services_types.h $(VDSP)/Blackfin/include/sys/exception.h $(VDSP)/Blackfin/include/stdint.h ../src/l502_cdefs.h ../src/l502_fpga.h ../src/l502_fpga_regs.h ../src/l502_hdma.h 
	@echo "..\src\l502_init.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_init.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_init.doj -MM

Release/l502_params.doj :../src/l502_params.c $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/stdlib_bf.h ../src/l502_global.h ../src/l502_bf_cmd_defs.h ../src/l502_cmd.h ../src/l502_fpga.h ../src/l502_fpga_regs.h ../src/l502_params.h ../src/l502_defs.h ../src/l502_stream.h 
	@echo "..\src\l502_params.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_params.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_params.doj -MM

Release/l502_sport_tx.doj :../src/l502_sport_tx.c $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h $(VDSP)/Blackfin/include/sys/exception.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h ../src/l502_sport_tx.h ../src/l502_cdefs.h ../src/l502_fpga_regs.h ../src/l502_fpga.h ../src/l502_bf_cmd_defs.h ../src/l502_defs.h ../src/l502_stream.h 
	@echo "..\src\l502_sport_tx.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_sport_tx.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_sport_tx.doj -MM

Release/l502_stream.doj :../src/l502_stream.c $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h $(VDSP)/Blackfin/include/sys/exception.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h ../src/l502_cdefs.h ../src/l502_cmd.h ../src/l502_bf_cmd_defs.h ../src/l502_fpga.h ../src/l502_fpga_regs.h ../src/l502_defs.h ../src/l502_global.h ../src/l502_hdma.h ../src/l502_sport_tx.h ../src/l502_user_process.h ../src/l502_stream.h ../src/l502_sport_rx.h l502_sdram_noinit.h 
	@echo "..\src\l502_stream.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_stream.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_stream.doj -MM

Release/l502_tests.doj :../src/l502_tests.c $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/cdefBF523.h $(VDSP)/Blackfin/include/defBF523.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/defBF52x_base.h $(VDSP)/Blackfin/include/cdef_LPBlackfin.h $(VDSP)/Blackfin/include/cdefBF52x_base.h $(VDSP)/Blackfin/include/sys/exception.h ../src/l502_cmd.h $(VDSP)/Blackfin/include/stdint.h ../src/l502_bf_cmd_defs.h ../src/l502_fpga.h ../src/l502_fpga_regs.h ../src/l502_sport_tx.h $(VDSP)/Blackfin/include/string.h 
	@echo "..\src\l502_tests.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_tests.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_tests.doj -MM

Release/l502_user_data.doj :../src/l502_user_data.c $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/math.h $(VDSP)/Blackfin/include/ymath.h $(VDSP)/Blackfin/include/math_bf.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fract_math.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h $(VDSP)/Blackfin/include/fr2x16_math.h $(VDSP)/Blackfin/include/fr2x16_base.h $(VDSP)/Blackfin/include/r2x16_base.h ../src/l502_bf_cmd_defs.h ../src/l502_params.h ../src/l502_defs.h ../src/l502_async.h ../src/l502_sport_rx.h ../src/l502_stream.h ../src/l502_user_data.h ../src/l502_user_types.h l502_sdram_noinit.h 
	@echo "..\src\l502_user_data.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_user_data.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_user_data.doj -MM

Release/l502_user_process.doj :../src/l502_user_process.c $(VDSP)/Blackfin/include/stdlib.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/stdlib_bf.h $(VDSP)/Blackfin/include/string.h $(VDSP)/Blackfin/include/math.h $(VDSP)/Blackfin/include/ymath.h $(VDSP)/Blackfin/include/math_bf.h $(VDSP)/Blackfin/include/fract_typedef.h $(VDSP)/Blackfin/include/fract_math.h $(VDSP)/Blackfin/include/ccblkfn.h $(VDSP)/Blackfin/include/builtins.h $(VDSP)/Blackfin/include/sys/builtins_support.h $(VDSP)/Blackfin/include/fr2x16_typedef.h $(VDSP)/Blackfin/include/r2x16_typedef.h $(VDSP)/Blackfin/include/raw_typedef.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/mc_typedef.h $(VDSP)/Blackfin/include/fr2x16_math.h $(VDSP)/Blackfin/include/fr2x16_base.h $(VDSP)/Blackfin/include/r2x16_base.h ../src/l502_stream.h $(VDSP)/Blackfin/include/stdint.h ../src/l502_hdma.h ../src/l502_sport_tx.h ../src/l502_cmd.h ../src/l502_bf_cmd_defs.h ../src/l502_params.h ../src/l502_defs.h ../src/l502_user_types.h ../src/l502_user_data.h ../src/l502_async.h 
	@echo "..\src\l502_user_process.c"
	$(VDSP)/ccblkfn.exe -c ..\src\l502_user_process.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\l502_user_process.doj -MM

Release/main.doj :../src/main.c ../src/l502_cdefs.h ../src/l502_global.h $(VDSP)/Blackfin/include/stdint.h $(VDSP)/Blackfin/include/yvals.h ../src/l502_bf_cmd_defs.h ../src/l502_cmd.h 
	@echo "..\src\main.c"
	$(VDSP)/ccblkfn.exe -c ..\src\main.c -file-attr ProjectName=l502-bf -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF523 -o .\Release\main.doj -MM

./Release/l502-bf.dxe :./l502-bf.ldf ./Release/l502-bf_basiccrt.doj $(VDSP)/Blackfin/lib/bf523_rev_any/libprofile532y.dlb ./Release/l502-bf_heaptab.doj ./Release/l502_async.doj ./Release/l502_cmd.doj ./Release/l502_fpga.doj ./Release/l502_hdma.doj ./Release/l502_init.doj ./Release/l502_params.doj ./Release/l502_sport_tx.doj ./Release/l502_stream.doj ./Release/l502_tests.doj ./Release/l502_user_data.doj ./Release/l502_user_process.doj ./Release/main.doj $(VDSP)/Blackfin/lib/cplbtab523.doj $(VDSP)/Blackfin/lib/bf523_rev_any/libsmall532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libio532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libc532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libevent532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libssl527y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libdrv527y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libusb527y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libf64ieee532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libdsp532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libsftflt532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libetsi532y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/libftl527y.dlb $(VDSP)/Blackfin/lib/bf523_rev_any/idle532mty.doj $(VDSP)/Blackfin/lib/bf523_rev_any/librt_fileio532y.dlb 
	@echo "Linking..."
	$(VDSP)/ccblkfn.exe .\Release\l502-bf_basiccrt.doj .\Release\l502-bf_heaptab.doj .\Release\l502_async.doj .\Release\l502_cmd.doj .\Release\l502_fpga.doj .\Release\l502_hdma.doj .\Release\l502_init.doj .\Release\l502_params.doj .\Release\l502_sport_tx.doj .\Release\l502_stream.doj .\Release\l502_tests.doj .\Release\l502_user_data.doj .\Release\l502_user_process.doj .\Release\main.doj -T .\l502-bf.ldf -flags-link -ip -L .\Release -flags-link -MDUSER_CRT=ADI_QUOTEl502-bf_basiccrt.dojADI_QUOTE,-MDUSE_CACHE,-MDUSE_INSTRUCTION_CACHE -flags-link -e -flags-link -MDUSE_CACHE -flags-link -od,.\Release -o .\Release\l502-bf.dxe -proc ADSP-BF523 -flags-link -MM

./Release/l502-bf.ldr :./Release/l502-bf.dxe 
	@echo "Creating loader file..."
	$(VDSP)/elfloader.exe .\Release\l502-bf.dxe -b Flash -f BINARY -Width 16 -o .\Release\l502-bf.ldr -No2Kernel -proc ADSP-BF523 -MM

endif

ifeq ($(MAKECMDGOALS),l502-bf_Release_clean)

l502-bf_Release_clean:
	-$(RM) ".\Release\l502-bf_basiccrt.doj"
	-$(RM) "Release\l502-bf_heaptab.doj"
	-$(RM) "Release\l502_async.doj"
	-$(RM) "Release\l502_cmd.doj"
	-$(RM) "Release\l502_fpga.doj"
	-$(RM) "Release\l502_hdma.doj"
	-$(RM) "Release\l502_init.doj"
	-$(RM) "Release\l502_params.doj"
	-$(RM) "Release\l502_sport_tx.doj"
	-$(RM) "Release\l502_stream.doj"
	-$(RM) "Release\l502_tests.doj"
	-$(RM) "Release\l502_user_data.doj"
	-$(RM) "Release\l502_user_process.doj"
	-$(RM) "Release\main.doj"
	-$(RM) ".\Release\l502-bf.dxe"
	-$(RM) ".\Release\l502-bf.ldr"
	-$(RM) ".\Release\*.ipa"
	-$(RM) ".\Release\*.opa"
	-$(RM) ".\Release\*.ti"
	-$(RM) ".\Release\*.pgi"
	-$(RM) ".\*.rbld"

endif


